const IMAGES = [
  {
    src: "https://i.imgur.com/hyumLxF.jpg",
    thumbnail: "https://i.imgur.com/hyumLxF.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    caption: "Shanti Outside Living Room",
  },
  {
    src: "./images/allimg/2.jpg",
    thumbnail: "./images/allimg/2.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    caption: "Shanti Outside Living Room",
  },

  {
    src: "./images/allimg/3.jpg",
    thumbnail: "./images/allimg/3.jpg",
    caption: "Shanti Living Room",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/4.jpg",
    thumbnail: "./images/allimg/4.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    caption: "Shanti Living Room",
  },
  {
    src: "./images/allimg/5.jpg",
    thumbnail: "./images/allimg/5.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    // tags: [
    //   { value: "Ocean", title: "Ocean" },
    //   { value: "People", title: "People" },
    // ],
    caption: "Shanti Awards",
  },

  {
    src: "./images/allimg/6.jpg",
    thumbnail: "./images/allimg/6.jpg",
    caption: "Shanti 8 bed dorm",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/7.jpg",
    thumbnail: "./images/allimg/7.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    caption: "Shanti 8 bed dorm",
  },
  {
    src: "./images/allimg/8.jpg",
    thumbnail: "./images/allimg/8.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    // tags: [
    //   { value: "Ocean", title: "Ocean" },
    //   { value: "People", title: "People" },
    // ],
    caption: "Shanti 8 bed dorm",
  },

  {
    src: "./images/allimg/9.jpg",
    thumbnail: "./images/allimg/9.jpg",
    caption: "Shanti 8 bed dorm",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/10.jpg",
    thumbnail: "./images/allimg/10.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    caption: "Shanti 8 bed dorm",
  },
  {
    src: "./images/allimg/11.jpg",
    thumbnail: "./images/allimg/11.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    // tags: [
    //   { value: "Ocean", title: "Ocean" },
    //   { value: "People", title: "People" },
    // ],
    caption: "Shanti 4 bed dorm- The Orange",
  },

  {
    src: "./images/allimg/12.jpg",
    thumbnail: "./images/allimg/12.jpg",
    caption: "Shanti 4 bed dorm- The Orange",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/13.jpg",
    thumbnail: "./images/allimg/13.jpg",
    caption: "Shanti 4 bed dorm- The Orange",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/14.jpg",
    thumbnail: "./images/allimg/14.jpg",
    caption: "Shanti 4 bed dorm- The Orange",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/15.jpg",
    thumbnail: "./images/allimg/15.jpg",
    caption: "Shanti 4 bed dorm- The Orange",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/16.jpg",
    thumbnail: "./images/allimg/16.jpg",
    caption: "Shanti 4 bed dorm- The Green",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/17.jpg",
    thumbnail: "./images/allimg/17.jpg",
    caption: "Shanti 4 bed dorm- The Yellow",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/18.jpg",
    thumbnail: "./images/allimg/18.jpg",
    caption: "Shanti Private Double Room",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/19.jpg",
    thumbnail: "./images/allimg/19.jpg",
    caption: "Shanti Private Double Room",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/20.jpg",
    thumbnail: "./images/allimg/20.jpg",
    caption: "Shanti Kitchen",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/21.jpg",
    thumbnail: "./images/allimg/21.jpg",
    caption: "Shanti Kitchen",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/22.jpg",
    thumbnail: "./images/allimg/22.jpg",
    caption: "Shanti Yard",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/23.jpg",
    thumbnail: "./images/allimg/23.jpg",
    caption: "Shanti Yard",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/24.jpg",
    thumbnail: "./images/allimg/24.jpg",
    caption: "Shanti Yard",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/25.jpg",
    thumbnail: "./images/allimg/25.jpg",
    caption: "Shanti Shared Bathroom",
    thumbnailWidth: 280,
    thumbnailHeight: 174,
  },

  {
    src: "./images/allimg/26.jpg",
    thumbnail: "./images/allimg/26.jpg",
    caption: "Shanti Shared Bathroom",
    thumbnailWidth: 280,
    thumbnailHeight: 174,
  },
  {
    src: "./images/allimg/27.jpg",
    thumbnail: "./images/allimg/27.jpg",
    caption: "Shanti Hostel",
    thumbnailWidth: 280,
    thumbnailHeight: 174,
  },
]

export default IMAGES
