const IMAGES = [
  {
    src: " https://i.imgur.com/5I7W9LJ.jpg",
    thumbnail: "https://i.imgur.com/VDa1Uh3.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    caption: "Shanti Outside Living Room",
  },
  {
    src: "https://i.imgur.com/NUzfSIq.jpg",
    thumbnail: "https://i.imgur.com/zkaXDDq.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    caption: "Shanti Outside Living Room",
  },

  {
    src: "https://i.imgur.com/D98r3p0.jpg",
    thumbnail: "https://i.imgur.com/IbLT9og.jpg",
    caption: "Shanti Living Room",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/mIeumjk.jpg",
    thumbnail: "https://i.imgur.com/fKNbAyx.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    caption: "Shanti Living Room",
  },
  {
    src: "https://i.imgur.com/amshwrB.jpg",
    thumbnail: "https://i.imgur.com/KQI02iR.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    caption: "Shanti Awards",
  },

  {
    src: "https://i.imgur.com/vWJ9stB.jpg",
    thumbnail: "https://i.imgur.com/ETMpdfL.jpg",
    caption: "Shanti 8 bed dorm",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/hszO9x0.jpg",
    thumbnail: "https://i.imgur.com/LKOn5Px.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    caption: "Shanti 8 bed dorm",
  },
  {
    src: "https://i.imgur.com/Tx0nE6K.jpg",
    thumbnail: "https://i.imgur.com/F7FPg7q.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    caption: "Shanti 8 bed dorm",
  },

  {
    src: "https://i.imgur.com/zCGdhlu.jpg",
    thumbnail: "https://i.imgur.com/h3UqskJ.jpg",
    caption: "Shanti 8 bed dorm",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/qiQbaeR.jpg",
    thumbnail: "https://i.imgur.com/ukA1QyC.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    caption: "Shanti 8 bed dorm",
  },
  {
    src: "https://i.imgur.com/fXBMfNh.jpg",
    thumbnail: "https://i.imgur.com/yh4mL1r.jpg",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
    caption: "Shanti 4 bed dorm- The Orange",
  },

  {
    src: "https://i.imgur.com/YSo0wTU.jpg",
    thumbnail: "https://i.imgur.com/piHSFGo.jpg",
    caption: "Shanti 4 bed dorm- The Orange",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/nqKzCTG.jpg",
    thumbnail: "https://i.imgur.com/bndJF4F.jpg",
    caption: "Shanti 4 bed dorm- The Orange",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/YFIwdsb.jpg",
    thumbnail: "https://i.imgur.com/YeFxL8o.jpg",
    caption: "Shanti 4 bed dorm- The Orange",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/OYYIVtc.jpg",
    thumbnail: "https://i.imgur.com/cvsLg7Y.jpg",
    caption: "Shanti 4 bed dorm- The Orange",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/qLewops.jpg",
    thumbnail: "https://i.imgur.com/9KFMZSz.jpg",
    caption: "Shanti 4 bed dorm- The Green",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/TMWUrAb.jpg",
    thumbnail: "https://i.imgur.com/ONCyWJd.jpg",
    caption: "Shanti 4 bed dorm- The Yellow",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/N2uTBMz.jpg",
    thumbnail: "https://i.imgur.com/Vc6LYhf.jpg",
    caption: "Shanti Private Double Room",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/8Ml2sq8.jpg",
    thumbnail: "https://i.imgur.com/wSHWWHU.jpg",
    caption: "Shanti Private Double Room",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/YER7TF0.jpg",
    thumbnail: "https://i.imgur.com/0cewu6e.jpg",
    caption: "Shanti Kitchen",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/hvkwzPr.jpg",
    thumbnail: "https://i.imgur.com/Yb8Qvmh.jpg",
    caption: "Shanti Kitchen",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/oj9z3ym.jpg",
    thumbnail: "https://i.imgur.com/oj9z3ym.jpg",
    caption: "Shanti Yard",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/X45RwyO.jpg",
    thumbnail: "https://i.imgur.com/LVPlZur.jpg",
    caption: "Shanti Yard",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/3OnchAr.jpg",
    thumbnail: "https://i.imgur.com/KKz5R2a.jpg",
    caption: "Shanti Yard",
    thumbnailWidth: 290,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/LANIDge.jpg",
    thumbnail: "https://i.imgur.com/gYsBoiy.jpg",
    caption: "Shanti Shared Bathroom",
    thumbnailWidth: 280,
    thumbnailHeight: 174,
  },

  {
    src: "https://i.imgur.com/1BaonYT.jpg",
    thumbnail: "https://i.imgur.com/YqEyi72.jpg",
    caption: "Shanti Shared Bathroom",
    thumbnailWidth: 280,
    thumbnailHeight: 174,
  },
  {
    src: "https://i.imgur.com/b7KfsxQ.jpg",
    thumbnail: "https://i.imgur.com/KZvJmBr.jpg",
    caption: "Shanti Hostel",
    thumbnailWidth: 280,
    thumbnailHeight: 174,
  },
];

export default IMAGES;
